# Generated by Django 4.1.3 on 2022-11-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('addr', models.TextField()),
                ('marks', models.FloatField()),
            ],
        ),
    ]
