# Generated by Django 4.0.4 on 2022-11-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0002_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
