# Generated by Django 4.1.4 on 2022-12-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('addr', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('mob_no', models.CharField(max_length=12)),
                ('department', models.CharField(max_length=50)),
                ('sal', models.FloatField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
