# Generated by Django 4.1.4 on 2022-12-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0002_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
