# Generated by Django 4.1.4 on 2022-12-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0003_remove_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('work_sheet', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
