# Generated by Django 4.1.4 on 2022-12-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0004_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='sr_no',
        ),
    ]
